apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: multi-platform-suite-component-nwgd
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/multi-platform-build-tenant/multi-platform-suite-application-twov/multi-platform-suite-component-nwgd@sha256:ede7a0adc731569e347c740418dc8e0cadcf8d7d9fcaed7e8f3e7c4d86149664
        name: my-go
        resources: {}
status: {}
